# This workflow builds golang binaries and adds them to a release

name: Go

on:
  release:
    types: [published]

jobs:

  publish_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
        env GOOS=darwin GOARCH=amd64 go build -o "ovh-spark-submit_darwin_amd64"
        env GOOS=darwin GOARCH=arm64 go build -o "ovh-spark-submit_darwin_arm64"
        env GOOS=linux GOARCH=386 go build -o "ovh-spark-submit_linux_386"
        env GOOS=linux GOARCH=amd64 go build -o "ovh-spark-submit_linux_amd64"
        env GOOS=windows GOARCH=386 go build -o "ovh-spark-submit_windows_386"
        env GOOS=windows GOARCH=amd64 go build -o "ovh-spark-submit_windows_amd64"

    - name: Test
      run: go test -v ./...

    - name: Add binary
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
      run: gh release upload ${{ github.ref_name }} ovh-spark-submit_*

    - name: Publish release
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
      run: gh release edit ${{ github.ref_name }} --draft=false --latest
