# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: env GOOS=linux GOARCH=amd64 go build -v -o "ovh-spark-submit_linux_amd64"

    - name: Test
      run: go test -v ./...
    
    - name: Add binary
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
      run: gh release upload ${{ github.ref_name }} "ovh-spark-submit_linux_amd64"

    - name: Publish release
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
      run: gh release edit ${{ github.ref_name }} --draft=false --latest
  
